setupCommonPipelineEnvironment script:this
#Steps Specific Configuration
general:
  changeManagement:
    endpoint: 'https://<backend-system>/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV'
    credentialsId: 'CM'
    type: 'SOLMAN'
steps:
  mtaBuild:
    buildTarget: 'NEO'
  transportRequestCreate:
    developmentSystemId: '<value for developmentSystemId>'
  transportRequestUploadFile:
    applicationId: 'HCP'
setupCommonPipelineEnvironment script:this
